### ISSUE TITLE
Negation of periodic extension missing in symmetrizePattern

### ISSUE THREAD

**Issue by martka** [EMS-TU-Ilmenau/EADF#11]
When the sampled (or "measured") pattern is periodically extended the values have to be negated. It  appears to me that this is not done in symmetrizePattern().
The reason for negation is the "flipping" of the polarization vectors for the extended co-elevation angles. Although the pair of spherical coordinates (az=42°, co-ele=12°) and (az=42°+180°, co-ele=-12°) denote the same point on a sphere, the definition of polarization vectors of the electromagnetic field is different (opposite orientation or multiplied by -1).
In the EADF paper of Del Galdo and Landmann (2) this fact is hidden a bit "B_r comprises the same information contained by -(!) B". Its a bit clearer in Landmanns thesis.
Without the negation a discontinuity appears at the poles - the field vector would suddenly change its orientation.

**Comment by SebastianSemper** [comment]
I know! for my exmaples I did not see any errors. Will be fixed soon. Is there any way how we can test this?
