### ISSUE TITLE
Dipoles for synthetic arrays

### ISSUE THREAD

**Issue by SebastianSemper** [EMS-TU-Ilmenau/EADF#21]
We would like to be able to provide some kind of more physically correct dipole pattern for the synthetic arrays. the only place where we need to figure this out is in arrays.generateUniformArbitrary

**Comment by ChristophWWagner** [comment]
Since the pattern of a Hertz Dipole can be described analytically, the choice seems good for that.

What is the final goal of this issue, that you have in mind? Should a parametrically generated EADF be returned for dipoles of given parameters?

**Comment by MichaelDoebereiner** [comment]
I've found a description of the beampattern of a dipole depending on the frequency and the length of the dipole. This allows us to create more realistic arrays.

**Comment by SebastianSemper** [comment]
Done, closing.
