### ISSUE TITLE
Calculate Grid densities

### ISSUE THREAD

**Issue by SebastianSemper** [EMS-TU-Ilmenau/EADF#28]
We use a grid in angular x frequency domain to represent the effective aperture of antennas. As such the information we store about the array is naturally bandlimited. As such it cannot be arbitrarily complicated. The spectrum of the data tells us the largest frequency present in the signal, which tells us the minimum sampling frequency in angle and frequency we have to use in order to *OBEY* Nyquist.

So during the calculation of `g(theta, f) = a(theta, f)^H * x` we only need a certain grid density in theta and f to exactly represent the function g. This density can be inferred from the spectral data we have collected about the array.

A similar argument can be made about the derivatives `a'` and `a''`.

**Comment by ChristophWWagner** [comment]
Do you mean to determine the parameters of the underlying grid for both angular and the frequency grid?

If so, and depending on the exact intention, this could possibly fall off as a side-achievement along the way, just by fixing #52.

Please elaborate more on motivation and exact intent for this issue. I'd be interested to tackle #52 early on (since it currently is a game-breaker for the HFSS import)

**Comment by SebastianSemper** [comment]
> @SebastianSemper, Please elaborate more on motivation and exact intent for this issue. I'd be interested to tackle #52 early on (since it currently is a game-breaker for the HFSS import)

I edited the description of the issue. As you can see, the issue is not related to #52.

**Comment by ChristophWWagner** [comment]
Ok. Thanks for clarifying. Since you did not expressly say whether grid parameters are beneficial for this, just comment on #52 in case they are. Then we'll figure out the details in #52.

**Comment by SebastianSemper** [comment]
We should not only return the regularly sampled grid, but also a minimal lebedev grid, since this has great advantages during correlation steps with the antenna patterns.
