### ISSUE TITLE
Calculating gradientNarrowBand for multiple angles

### ISSUE THREAD

**Issue by MichaelDoebereiner** [EMS-TU-Ilmenau/EADF#37]
Calculating the gradient for multiple angles at once, does only work when the number of both angles is the same.

core.py _evalNarrowBand
`if arrAzi.shape[0] != arrCoEle.shape[0]:
            logging.error(
                "patternNarrowBand: supplied angle arrays have size %d and %d."
                % (arrAzi.shape[0], arrCoEle.shape[0])
            )
            return`

**Comment by SebastianSemper** [comment]
this is expected.
