### ISSUE TITLE
Shifted/flipped beampattern and gradients

### ISSUE THREAD

**Issue by MichaelDoebereiner** [EMS-TU-Ilmenau/EADF#40]
The beampattern and gradients calculated by patternNarrowBand and gradientNarrowBand seem to be flipped/shifted along the azimuth and elevation direction. See the attached comparisons to the Matlab implementation.

Beampattern
![BP](https://user-images.githubusercontent.com/44783621/74517199-fb74de00-4f11-11ea-958f-386c62aacc3d.PNG)
gradAzi
![gradAzi](https://user-images.githubusercontent.com/44783621/74517192-fa43b100-4f11-11ea-94cb-5d77a56c5840.PNG)
gradEle
![gradEle](https://user-images.githubusercontent.com/44783621/74517196-fadc4780-4f11-11ea-83ad-2c8177a0a1a1.PNG)

**Comment by SebastianSemper** [comment]
solved.
