### ISSUE TITLE
Beef up the Demos!

### ISSUE THREAD

**Issue by SebastianSemper** [EMS-TU-Ilmenau/EADF#48]
The demo-section in our documentation deserves some love. We should add some more explanations in the respective files and we should include the plots directly in the documentation, so that the user can see results even without running them. For this we have a _static directory residing in doc/.

**Comment by ChristophWWagner** [comment]
> The demo-section in our documentation deserves some love.

❤️

**Comment by SebastianSemper** [comment]
Duplicate of #60. Closing.
