### ISSUE TITLE
EADF.__init__ fails when sampling is not aligned to the north pole

### ISSUE THREAD

**Issue by ChristophWWagner** [EMS-TU-Ilmenau/EADF#52]
Assuming you want to create an EADF object from a tensor object, which is sampled equidistant and fullly (including the poles), then the creation of the object fails as soon as the poles are not exactly at the edges of the given support vector (0 for north and $pi$ for south pole).

This is for no apparent reason, since the usage definition does not pose any requirements other than that the poles need to be sampled. Beginning somewhere along the CoElevation should be supported indeed.

A quick look reveals that at the issue is most probably caused by the logic at https://github.com/EMS-TU-Ilmenau/EADF/blob/a17d6eb7ddc49bbbe147e82e97784ce26c597a70/eadf/eadf.py#L1177
which lacks generality.

The suggestion is to replace this logic with the following checks:
  1. Make sure that the support vector entries are wrapped to the interval $]-\pi\dots\pi]$ before beginning
  2. Check, if the north and the south pole can be found in the specified data (support vector contains the entries $0$ and $pi$)
  3. Check, if the support vector is equidistant and fully sampled between $(0 \dots \pi)$. A suggestion on how to accomplish this is:
     ```python
      vec_increments = np.unique(np.diff(vec_support))
      assert vec_increments.size == 1 # checks for equidistant sampling due to `np.diff`
      assert (vec_increments.min() <= 0) & (vec_increments.max() >= pi)
      assert abs(vec_increments[0]) == pi / (abs(argwhere(vec_support == pi) - argwhere(vec_support == 0)) - 1)
      ```
   4. Recreate the support vector using the parameters revealed in previous step (3.) and determine the location of the support, e.g. using `argsort` and `searchsorted`. Then reorder the tensor data.

This increases robustness of the implementation regarding the following cases (not complete:
 * support for cases where the sphere sampling is overcomplete or misaligned (but properly sampled)
 * support for cases where the support is given in the wrong direction (e.g. from south- to north pole)
 * support for cases where the support is defined in the wrong order (one could imagine this to happen during imports, if the file format being imported from is prone to such mixups)

BR
Christoph

**Comment by SebastianSemper** [comment]
Very well!

I will introduce a dedicated method that checks the input data for consistency. This should also tremendously clean up the now all to loong anyway `__init()__`.

**Comment by SebastianSemper** [comment]
In dev0.4 I just added a commit which introduces more consistent checks of the input-data. However regarding your issue I think we should keep the data one has to supply to the constructor as rigid as possible. First, this makes consistency checks during `__init__` more transparent, since the supplied data is easier to verify. Second it keeps the complexity of input data handling out of the `__init__` and in the respective importers -- I think this is why we have them in the first place.

So I added a more explicit description of the expected input data, which directly states that along co-elevation the first and last samples have to be the north/south pole respectively.

**Comment by ChristophWWagner** [comment]
I strongly advise against making this a RTFM issue due to unpracticality. In my example here, I, as a user, feed fully sampled (poles included) .csv exports from HFSS into the `fromHFSS` importer. The data is imported fine but the EADF container refuses to use it and the user has no chance of actually fixing this. Well, one could take vim and edit the crap out of them .csv files.

Another case is when files contain Elevation rather than CoElevation. Where do you suggest to handle this? For the EADF initializer it is probably too general, but for the importer it is probably too specific since then all importers need those options.

In that sense, along with your decision to make the code not care, comes the problem of solving these data representation situations, that a user cannot deal with.

I propose adding a `stringency='loose'` switch, which, if given, performs a small set of general operations that help the user in that case by modifying the data supplied to `EAD.__init__()` in a way that it becomes importable. Implementaion could be as easy as having this switch call a helper function in a completely different submodule, so the  EADF.__init__()` stays "lean". Then, the strict enforcement currently is highly preferrable.

PS: Does the current state of code actually verify somewhere if the grids are regular and monotonic?  If not that might cause some ill behaviour going unnoticed at some point.

**Comment by ChristophWWagner** [comment]
Issue is resolved in current `dev0.4` branch
