### ISSUE TITLE
Introduction of SI-unit awareness

### ISSUE THREAD

**Issue by ChristophWWagner** [EMS-TU-Ilmenau/EADF#53]
Since I stumbled across both beauty and havoc in also both having and not having SI-unit annotations for actual values while implementing the HFSS importer, I'd like to open this one for discussion.

I see the following benefits:
 * Less discrepancies when dealing with physical quantities
 * Less relying on intransparent *you-have-to-call-this-with-that-coding* conventions, enforced by RTFM
 * self-awareness of code regarding "presentation layer" issues leads to agnostic handling of such cases
 * Handling of units and integration into numpy is already done by the `pint` package

I see the following downsides:
 * Implementation adds new complexity in having to glue existing stuff to pint
 * Mostly importers and higher-level applications (e.g. geometry of wave propagation issues in arrays, etc.) would profit from this,

My stance:
This kind of information is usually already present to the importer (if the data format supports it -- but since we actually aim at making "self-aware data" the default in science this should be imperative). In applications regarding array signal processing and -design, most certainly this kind of meta information is required at some point. Therefore, making the EADF container support unit and magnitude metainformation, as provided by `pint`, seems desirable to me.

What do you think?

BR Christoph

**Comment by SebastianSemper** [comment]
It is indeed an interesting idea. I really think it would be a nice thing to have. However, I see some additional obstacles.

 - At some point we need to drop the physical intepretation of the data, since `cupy` is not handled by `pint`.
 - It is generally not true that the data format supports SI-unit information, or even contains it, since AFAIK our old matlab data does not contain the units of the data.

I think after the 0.4 we should create a branch where someone tries it out and reports back here in that issue or the respective pull-request how things are going. I agree with @ChristophWWagner that it might be some effort we have to exert, which at the end of the day might not be worth it.

**Comment by ChristophWWagner** [comment]
Sounds good to me.

Regarding your points
 * Dropping the unit information to get the underlying `ndarray` is as easy as using`<pinted_array>.m` and reintroducing units can be achieved by multiplying it like `<some_ndarray> * <pinted_array>.u`. Or in case you want to convert between two units: `<one_pinted_array>.to(<another_pinted_array>.u>). Ideally this is prepared once and then used accordingly throughout the package, so repeated conversions should not occur
 * I understand you are pointing out that out _current_ dataset just does not care at all about embedded unit information but rather leaves this to be handled in code by magic numbers and order-of-magnitude conventions. I agree. However, please understand my statement above more as how it *should* be, not how it is. In that sense I find it generally preferrable being explicit through unit-annotation rather than implicit through magic numbers and thelike.

**Comment by ChristophWWagner** [comment]
Type annotation is now handled as follows:

During __init__(), the arrays may be given as `ndarray` or as a `Quantity` (unit-flavoured `ndarray`) and will be given a default unit designator, if none is given (`ndarray` option). After checking consistency of the passed data (shapes, gridding, ...), this unit information is separated into `self.arr~` variables and `self.unit~` variables within the class, where `self.arr~` always is and only is of `ndarray` type and `self.unit~` always is a quantity.

So, if you want to retrieve only the magnitude values, everything stays as-is and nothing needs to change. However, if you -- for whatever reason -- feel the tickle to access unit information, simply resort to the `self.unit~` variant of a variable. If you like to restore the full quantity-annotated `ndarray`, simply multiply both (e.g. `self.arrFreq * self.unitFreq`) and you're set.

The variables are named:
  * `self.arrRawData` <-> `self.unitRawData`
  * `self.arrAzi` <-> `self.unitAzi`
  * `self.arrCoEle` <-> `self.unitCoEle`
  * `self.arrFreq` <-> `self.unitFreq`
  * `self.arrPos` <-> `self.unitPos`

**Comment by ChristophWWagner** [comment]
Issue is resolved in current `dev0.4` branch
