### ISSUE TITLE
Swap argument order of CoEle and Azi to reflect tensor layout

### ISSUE THREAD

**Issue by ChristophWWagner** [EMS-TU-Ilmenau/EADF#58]
The tensor layout currently is `(CoElevation, Azimuth, Freq, Polarization, Position)`, but most function arguments are in the order `(Azimuth, CoElevation, Freq, Polarization, Position)`. This is confusing at the least, since it leads to regular mixups.

Unfortunately, lots of things must be touched to make this consistent. What do you think?

**Comment by SebastianSemper** [comment]
Yes. I stumbled over this today several times. It is time to correct this.
