### ISSUE TITLE
use beampattern which can be described analytically for testing

### ISSUE THREAD

**Issue by MichaelDoebereiner** [EMS-TU-Ilmenau/EADF#59]
Implementation of an EADF demo using the analytically beampattern of patch antennas.
The same implementation is done in Matlab, so we can create EADFs of the same data in Matlab as well and can test the importers easily.

**Comment by SebastianSemper** [comment]
For this we should have a small data-set which was generated in Matlab checked into the repo. Or do we even still want this feature?

**Comment by SebastianSemper** [comment]
How far are we with this? Is this resolved?

**Comment by MichaelDoebereiner** [comment]
Yes, this was finished with the patchday branch. Now, there's a test comparing the imported EADF from Matlab with the patch array created in this package.
